# Generated by Django 4.2.4 on 2023-08-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auction',
            field=models.BooleanField(help_text='Отьметьте, если торг уместен', verbose_name='Торг'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='update_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата и время обновления'),
        ),
    ]
