# Generated by Django 4.2.4 on 2023-08-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0003_alter_advertisement_auction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время обновления'),
        ),
    ]
